### ISSUE TITLE
Change to use Facebook's API.

### ISSUE THREAD

**Issue by tommyclark** [mikegreen1995/Facebook-Message-Parser#7]
It's broken, mate

**Comment by mikegreen1995** [comment]
> It's broken, mate

Dear Mr Clark (@tommyclark ),

Thank you for taking the time to report this issue.

Please find the official response from our customer relations team regarding our use of Facebook's API (or lack thereof) in the README.

In summary, "not gonna happen, mate".

Kind regards,
Mike
